---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - jupyter.org
  resources:
  - jupyterhubs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jupyter.org
  resources:
  - jupyterhubs/finalizers
  verbs:
  - update
- apiGroups:
  - jupyter.org
  resources:
  - jupyterhubs/status
  verbs:
  - get
  - patch
  - update
